<a href="https://colab.research.google.com/github/kartikdhyani817/AI-CSV-Data-Analyst-Agent/blob/main/AI_CSV_Data_Analyst_Agent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving Sample - Superstore.csv to Sample - Superstore.csv

In [2]:
filename = list(uploaded.keys())[0]


df = pd.read_csv(filename, encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
df.info()
df.describe()

Rows: 9994
Columns: 21
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [4]:
print("Missing Values")

print(df.isnull().sum())

Missing Values
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [5]:
print("Column Names")

print(df.columns.tolist())

Column Names
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [6]:
summary = f"""
Dataset Summary

Rows: {df.shape[0]}

Columns: {df.shape[1]}

Columns Available:

{df.columns.tolist()}
"""

print(summary)

Dataset Summary

Rows: 9994

Columns: 21

Columns Available:

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [7]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

df = df.drop_duplicates()

print("Duplicates Removed")

Duplicate Rows: 0
Duplicates Removed

In [8]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent)

Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

In [9]:
print("DATA QUALITY REPORT")

print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing Values")

print(df.isnull().sum())

print("\nDuplicate Rows")

print(df.duplicated().sum())

DATA QUALITY REPORT

Rows: 9994
Columns: 21

Missing Values
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicate Rows
0

In [10]:
numerical_columns = df.select_dtypes(
    include=['int64', 'float64']
).columns

print(numerical_columns)

Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')

In [11]:
df[numerical_columns].describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [12]:
correlation = df[numerical_columns].corr()

correlation

               Row ID  Postal Code     Sales  Quantity  Discount    Profit
Row ID       1.000000     0.009671 -0.001359 -0.004016  0.013480  0.012497
Postal Code  0.009671     1.000000 -0.023854  0.012761  0.058443 -0.029961
Sales       -0.001359    -0.023854  1.000000  0.200795 -0.028190  0.479064
Quantity    -0.004016     0.012761  0.200795  1.000000  0.008623  0.066253
Discount     0.013480     0.058443 -0.028190  0.008623  1.000000 -0.219487
Profit       0.012497    -0.029961  0.479064  0.066253 -0.219487  1.000000

In [13]:
corr_pairs = correlation.unstack()

corr_pairs = corr_pairs.sort_values(
    ascending=False
)

print(corr_pairs.head(20))

Row ID       Row ID         1.000000
Discount     Discount       1.000000
Sales        Sales          1.000000
Postal Code  Postal Code    1.000000
Profit       Profit         1.000000
Quantity     Quantity       1.000000
Sales        Profit         0.479064
Profit       Sales          0.479064
Quantity     Sales          0.200795
Sales        Quantity       0.200795
Quantity     Profit         0.066253
Profit       Quantity       0.066253
Postal Code  Discount       0.058443
Discount     Postal Code    0.058443
             Row ID         0.013480
Row ID       Discount       0.013480
Postal Code  Quantity       0.012761
Quantity     Postal Code    0.012761
Row ID       Profit         0.012497
Profit       Row ID         0.012497
dtype: float64

In [14]:
categorical_columns = df.select_dtypes(
    include=['object']
).columns

for col in categorical_columns:

    print("\n", col)

    print(
        df[col].value_counts().head(5)
    )

 Order ID
Order ID
CA-2017-100111    14
CA-2017-157987    12
CA-2016-165330    11
US-2016-108504    11
US-2015-126977    10
Name: count, dtype: int64

 Order Date
Order Date
9/5/2016      38
9/2/2017      36
11/10/2016    35
12/1/2017     34
12/2/2017     34
Name: count, dtype: int64

 Ship Date
Ship Date
12/16/2015    35
9/26/2017     34
11/21/2017    32
12/6/2017     32
9/6/2017      30
Name: count, dtype: int64

 Ship Mode
Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

 Customer ID
Customer ID
WB-21850    37
MA-17560    34
JL-15835    34
PP-18955    34
CK-12205    32
Name: count, dtype: int64

 Customer Name
Customer Name
William Brown          37
Matt Abelman           34
John Lee               34
Paul Prost             34
Chloris Kastensmidt    32
Name: count, dtype: int64

 Segment
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

 Country
Country
United States    9994
Name: count, dtype: int64

 City
City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Seattle          428
Name: count, dtype: int64

 State
State
California      2001
New York        1128
Texas            985
Pennsylvania     587
Washington       506
Name: count, dtype: int64

 Region
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

 Product ID
Product ID
OFF-PA-10001970    19
TEC-AC-10003832    18
FUR-FU-10004270    16
FUR-CH-10002647    15
FUR-CH-10001146    15
Name: count, dtype: int64

 Category
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

 Sub-Category
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Name: count, dtype: int64

 Product Name
Product Name
Staple envelope            48
Staples                    46
Easy-staple paper          46
Avery Non-Stick Binders    20
Staples in misc. colors    19
Name: count, dtype: int64

In [15]:
insights = []

insights.append(
    f"Dataset contains {df.shape[0]} rows."
)

insights.append(
    f"Dataset contains {df.shape[1]} columns."
)

insights.append(
    f"Numerical Columns: {len(numerical_columns)}"
)

insights.append(
    f"Categorical Columns: {len(categorical_columns)}"
)

print("KEY INSIGHTS")

for i in insights:
    print("-", i)

KEY INSIGHTS
- Dataset contains 9994 rows.
- Dataset contains 21 columns.
- Numerical Columns: 6
- Categorical Columns: 15

In [16]:
report = "\n".join(insights)

with open(
    "dataset_insights.txt",
    "w",
    encoding="utf-8"
) as file:

    file.write(report)

print("Report Saved")

Report Saved